-- CTRL + /  ->빠른 주석
SELECT * FROM EMPLOYEES;
--PK는 EMPLOYEE_ID(중복X임)
--FK는 DEPARTMENT_ID (다른테이블의 주키, 중복O)

--특정 컬럼만 조회하려면 나열      //왜 오류!?!?!
SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER FROM EMPLOYEES;

--문자, 날짜는 왼쪽으로 표시, 숫자는 오른쪽에 나타납니다.
SELECT FIRST_NAME, HIRE_DATE, SALARY, COMMISSION_PCT FROM EMPLOYEES;

--숫자 컬럼은 * / + - 가 됩니다
SELECT FIRST_NAME, SALARY, SALARY + SALARY * 0.1 FROM EMPLOYEES;

--컬럼 별칭 (ALIAS)  //띄어쓰기 못함!
SELECT FIRST_NAME AS 이름, SALARY 급여, SALARY + SALARY * 0.1 AS 최종_급여 FROM EMPLOYEES;

--문자열 붙이기 //'는 문자열임. 출력할 때 쓰고 싶으면 ''으로.
SELECT FIRST_NAME || '''님의 급여는 ' || SALARY || '$입니다' AS SALARY FROM EMPLOYEES;

--DISCTINT 중복 제거
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES;  --조회된 데이터 기준으로 중복을 제거

--ROWIE(데이터 주소), ROWNUM(데이터에 조회된 순서)
SELECT EMPLOYEE_ID, FIRST_NAME, ROWID, ROWNUM FROM EMPLOYEES;