DESC AUTH;
SELECT * FROM AUTH;
DELETE FROM AUTH;
ROLLBACK;

DROP TABLE MEMBERS;
CREATE TABLE MEMBERS (
    MNO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    ADDRESS VARCHAR2(30),
    REGDATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE MEMBERS_SEQ NOCACHE;

SELECT * FROM MEMBERS;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS 이름,
       E.DEPARTMENT_ID AS 부서아이디,
       D.DEPARTMENT_NAME AS 부서명,
       E.SALARY AS 급여
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.EMPLOYEE_ID = 100;